
export const GET_ALL_TYPES = 'GET_ALL_TYPES';
export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const SEARCH_RECIPE = 'SEARCH_RECIPE'
export const GET_RECIPE_DETAILS = 'GET_RECIPE_DETAILS';
export const CREATE_RECIPE = 'CREATE_RECIPE'; 
export const RECIPES_ORDER_AND_FILTER = 'RECIPES_ORDER_AND_FILTER';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER';
export const SET_CURRENT_LIMIT = 'SET_CURRENT_LIMIT';
export const DELETE_RECIPE = 'DELETE_RECIPE';